name: Testing API
# on:
#   push:
#     branches: [workflow_testing_api]
#   pull_request_target:
#     branches: [workflow_testing_api]
on: [push, pull_request_target]
jobs:
  testing-api:
    name: Testing-api in Github Actions
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write # need this for OIDC  
      contents: read
    env:
      AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Creating and activating virtualenv
        run: |
          pip install pipenv
          pipenv install
          pipenv run python
      - name: Installing dependencies
        run: |
          pip install dvc[s3]
          pip install -r requirements_test.txt
          export AWS_IAM_ROLE=$(python utilities/setter_role.py)
          export AWS_REGION=$(python utilities/setter_region.py)
      # Recomendacion para usar variables de entorno en memoria:
      # https://securitylab.github.com/research/github-actions-untrusted-input/#:~:text=variable%20de%20entorno-,intermedia,-%3A
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-session-name: awstestingsession
          aws-region: "${AWS_REGION}"
          role-to-assume: "${AWS_IAM_ROLE}"
      - name: Test API
        run: |
          dvc pull model/model.pkl -r model-tracker
          pytest tests.py


# jobs:
#   sync:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@v2
     
#       - name: Connect to AWS
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           role-session-name: awssyncsession
#           role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
#           aws-region: ${{ secrets.AWS_REGION }}
     
#       - name: sync bucket
#         run: aws s3 sync ./files/ s3://${{ secrets.AWS_BUCKET_NAME }} --delete