name: Testing API
on: [push, pull_request]
jobs:
  testing-api:
    runs-on: ubuntu-latest
    # env:
    #   SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }} # variable que definimos dentro de Dependabot secrets in secrets and variables in repository
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Creating and activating virtualenv
        run: |
          pip install pipenv
          pipenv install
          pipenv run python
      - name: Installing dependencies
        run: |
          pip install dvc[s3]
          pip install -r requirements_test.txt
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: echo ${{ secrets.AWS_ACCESS_KEY_ID }} | base64 -d
          aws-secret-access-key: echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} | base64 -d
          aws-region: eu-west-1
      - name: Test API
        run: |
          dvc pull model/model.pkl -r model-tracker
          pytest tests.py

      # - name: Install Python, pipenv and Pipfile packages
      #   uses: palewire/install-python-pipenv-pipfile@v2
      #   with:
      #     python-version: 3.10.0