name: Testing API

on:
  push:
    branches: [workflow_testing_api]
  pull_request:
    branches: [workflow_testing_api]

jobs:
  testing-api:
    name: Testing-api in Github Actions
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write # need this for OIDC  
      contents: read
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Creating and activating virtualenv
        run: |
          pip install pipenv
          pipenv install
          pipenv run python
      - name: Installing dependencies
        run: |
          pip install dvc[s3]
          pip install -r requirements_test.txt
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE || github.token }}
          aws-region: ${{ secrets.AWS_REGION || github.token }}
      - name: Test API
        run: |
          dvc pull model/model.pkl -r model-tracker
          pytest tests.py



# jobs:
#   sync:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@v2
     
#       - name: Connect to AWS
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           role-session-name: awssyncsession
#           role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
#           aws-region: ${{ secrets.AWS_REGION }}
     
#       - name: sync bucket
#         run: aws s3 sync ./files/ s3://${{ secrets.AWS_BUCKET_NAME }} --delete