name: Testing API
on: [push, pull_request]
jobs:
  testing-api:
    runs-on: ubuntu-latest
    # env:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #   SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }} # variable que definimos dentro de Dependabot secrets in secrets and variables in repository
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Creating and activating virtualenv
        run: |
          pip install pipenv
          pipenv install
          pipenv run python
      - name: Installing dependencies
        run: |
          pip install dvc[s3]
          pip install -r requirements_test.txt
      - name: Set environment variables secret
        run: |
          echo ${{ secrets.ENV_SECRET }} | base64 -d > .env
          pip install python-dotenv
          python load_dotenv.py    
      - name: Test API
        run: |
          dvc pull model/model.pkl -r model-tracker
          pytest tests.py



      # - name: Set AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     role-to-assume:
      #     aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-2