name: Testing API
on:
  workflow_dispatch:
  push:
    branches:
      - workflow_testing_api
  pull_request:
    branches:
      - workflow_testing_api
permissions:
  id-token: write # need this for OIDC  
  contents: read
jobs:
  testing-api:
    name: Testing-api in Github Actions
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-session-name: aws_testing_session
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Creating and activating pipenv
        run: |
          pip install pipenv
          pipenv install
          pipenv run python
      - name: Installing dependencies
        run: |
          pip install dvc[s3]
          pip install -r requirements_test.txt
      # Recomendacion para usar variables de entorno en memoria:
      # https://securitylab.github.com/research/github-actions-untrusted-input/#:~:text=variable%20de%20entorno-,intermedia,-%3A
      - name: Test API
        run: |
          dvc pull model/model.pkl -r model-tracker
          pytest tests.py


# jobs:
#   sync:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Repo
#         uses: actions/checkout@v2
     
#       - name: Connect to AWS
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           role-session-name: awssyncsession
#           role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
#           aws-region: ${{ secrets.AWS_REGION }}
     
#       - name: sync bucket
#         run: aws s3 sync ./files/ s3://${{ secrets.AWS_BUCKET_NAME }} --delete